-- Script de datos iniciales (sin datos demo)
-- Este archivo está vacío intencionalmente para evitar datos de ejemplo
-- Los usuarios se registrarán a través de la interfaz de la aplicación

-- Si necesitas crear un usuario administrador, puedes descomentar y modificar las siguientes líneas:
-- INSERT INTO usuarios (email, user_name, password_hash) 
-- VALUES (
--     'admin@tudominio.com', 
--     'Administrador', 
--     '$2a$10$XOPbrlUPQdwdJUpSrIF6X.LbE14qsMmKGhM1A8W9iqaG3vv1BD7WC'
-- ) ON CONFLICT (email) DO NOTHING;
